import { Montserrat, Inconsolata } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageTransition from "@/components/PageTransition";

const montserrat = Montserrat({
    subsets: ["latin"],
    display: 'swap',
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-montserrat'
});

const inconsolata = Inconsolata ({
  subsets: ["latin"],
  display: 'swap',
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-inconsolata'
});

export const metadata = {
  title: "UI Design & Frontend Development | Tim Breunig",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inconsolata.variable}`}>
        <Header />
        <PageTransition>
            {children}
        </PageTransition>
        <Footer />
      </body>
    </html>
  );
}
