import "./globals.css";
import { Outfit, Inconsolata } from 'next/font/google';
import { SpeedInsights } from "@vercel/speed-insights/next";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import { PageTransitionProvider } from "@/components/context/PageTransitionContext";
import LenisProvider from "@/components/LenisProvider";


const outfit = Outfit({
    subsets: ["latin"],
    display: 'swap',
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: '--font-outfit'
});


const inconsolata = Inconsolata ({
    subsets: ["latin"],
    display: 'swap',
    weight: ["200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-inconsolata'
});


export const metadata = {
    title: "UI Design & Frontend Development | Tim Breunig",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`relative ${outfit.variable} ${inconsolata.variable}`}>
                <a
                    href="#main-content"
                    className="sr-only focus:not-sr-only"
                >
                    Skip to main content
                </a>

                <LenisProvider>
                    <PageTransitionProvider>
                        <Header />

                        <main id="main-content">
                            <PageTransition>
                                {children}
                            </PageTransition>
                        </main>

                        <Footer />
                    </PageTransitionProvider>
                </LenisProvider>
                
                {/* <SpeedInsights /> */}
            </body>
        </html>
    );
}
